site_name: Documentations
site_description: 'La documentation du LXP'

site_dir: docs-build

theme:
  name: material
  locale: fr

extra_css:
  - 'css/extra.css'
extra_javascript:
  - js/extra.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lycee-Experimental

markdown_extensions:
  - admonition
  - codehilite:
      css_class: code
      use_pygments: false
      guess_lang: false
  - toc:
      permalink: true
